// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Routine.Api.Data;

namespace Routine.Api.Migrations
{
    [DbContext(typeof(RoutineDbContext))]
    [Migration("20200918071221_delete")]
    partial class delete
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Routine.Api.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Introduction")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b6ff3aa-d91d-4086-baea-5ec3564a31be"),
                            Introduction = "Greate Company",
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = new Guid("beeba841-f929-4f56-bfef-644bbc0e58d7"),
                            Introduction = "Don't be evil ",
                            Name = "Google"
                        },
                        new
                        {
                            Id = new Guid("9a2193e3-2c2d-4625-b346-fbc5e789f0ad"),
                            Introduction = "Fubao Company",
                            Name = "Alipapa"
                        });
                });

            modelBuilder.Entity("Routine.Api.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eaafdff3-cf19-4158-b225-8574a215b0f0"),
                            CompanyId = new Guid("9b6ff3aa-d91d-4086-baea-5ec3564a31be"),
                            DateOfBirth = new DateTime(1976, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "MSFT231",
                            FirstName = "Nick",
                            Gender = 1,
                            LastName = "Carter"
                        },
                        new
                        {
                            Id = new Guid("7d9e080d-e8ce-4e70-9d63-a3cccc93efa1"),
                            CompanyId = new Guid("9b6ff3aa-d91d-4086-baea-5ec3564a31be"),
                            DateOfBirth = new DateTime(1998, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "MSFT001",
                            FirstName = "Lisa",
                            Gender = 2,
                            LastName = "Jame"
                        },
                        new
                        {
                            Id = new Guid("e0c9f6d6-d36d-4544-95ae-6fb0c38a5f1f"),
                            CompanyId = new Guid("beeba841-f929-4f56-bfef-644bbc0e58d7"),
                            DateOfBirth = new DateTime(1988, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "G001",
                            FirstName = "Dick",
                            Gender = 1,
                            LastName = "Harden"
                        },
                        new
                        {
                            Id = new Guid("fb46e09f-6bd7-4a00-a50f-67c20f340cf9"),
                            CompanyId = new Guid("9a2193e3-2c2d-4625-b346-fbc5e789f0ad"),
                            DateOfBirth = new DateTime(1982, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "A001",
                            FirstName = "马",
                            Gender = 1,
                            LastName = "云"
                        },
                        new
                        {
                            Id = new Guid("fcecb660-ca39-46fe-8917-d4f032795821"),
                            CompanyId = new Guid("9a2193e3-2c2d-4625-b346-fbc5e789f0ad"),
                            DateOfBirth = new DateTime(1986, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "A002",
                            FirstName = "王",
                            Gender = 2,
                            LastName = "尼玛"
                        });
                });

            modelBuilder.Entity("Routine.Api.Entities.Employee", b =>
                {
                    b.HasOne("Routine.Api.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
